### ISSUE TITLE
Create document of user stories

### ISSUE THREAD

**Issue by egpbos** [dianna-ai/dianna-exploration#116]
[Link to the document](https://nlesc.sharepoint.com/:w:/s/DIANNA/EdoppPpmTTBKh0Mq-VdmvM8B_VeTFRzznZ3op-wo1cuBPA?e=qtGO5M)

Get them from #102.

Note: we discussed the difference between epics and user stories. We probably have been defining epics before and may now need to split them up into smaller or more actionable user stories.

@elboyran will write and @cwmeijer will review.

ToDo:

- [x] Contact Erik
- [x] Transfer and order from issue #102 as epics
- [x] Create an epic for images (e.g. DynaSlum context)
- [x] Contact Monika for feedback on the epic
- [x] Create user stories for images (e.g. DynaSlum context) (see issue #121)
- [x] Contact Monika for feedback on the user stories if she responded to the epic and is willing to collaborate.
- [x] Create user stories for text (e.g. NEWSGAG context) (see issue #117)

**Comment by elboyran** [comment]
Erik is on holiday until 5 September, To contact next week.

**Comment by elboyran** [comment]
The list of epics and stories are now in a [SharePoint document](https://nlesc.sharepoint.com/:w:/s/DIANNA/EdoppPpmTTBKh0Mq-VdmvM8B_VeTFRzznZ3op-wo1cuBPA?e=qtGO5M)

**Comment by elboyran** [comment]
Talked to Erik about NEWSGAG project. He pointed me out to the [project's publication](https://arxiv.org/abs/1810.00968). I will try to define some user stories from the paper's motivation and then he will check them out.

**Comment by elboyran** [comment]
Wrote some user stories for text (genre classification task) and waiting for feedback of Erik.

**Comment by elboyran** [comment]
Hi Erik,

Thanks for your feedback!

•	Yes, I want the user story to be from the name of a researcher (to be more personal as suggested by SCRUM experts). You are my researcher’s “proxy” 😉 , but if you are not happy I can jus remove the name.

•	Sorry for misspelling NEWSGAC.

•	I don’t see how the ranking shows the same information as a heatmap per letter. I would say one is aggregated version of the other and maybe only for the top N words, not for all.
Here you can see examples of heatmaps per word: https://github.com/albermax/innvestigate/blob/master/examples/notebooks/sentiment_analysis.ipynb
And rankings are shown on Figs.4 and 5 of your [paper](https://arxiv.org/pdf/1810.00968.pdf), right?

•	Doesn’t this story 
“ As a domain user I want to see an ML model’s prediction probabilities for classifying an article to a specific genre class and these probabilities for the rest of the genre classes to trust and understand the model’s decision making. ”
cover the probabilities of various classes?

•	Your final suggestion is quite nice indeed. This is a different way of explaining a model’s reasoning. The methods we chose do not support it natively, we have to think if we have time to include such functionality.

Best,
Elena

From: Erik Tjong Kim Sang <e.tjongkimsang@esciencecenter.nl> 
Sent: Tuesday, September 14, 2021 11:58 AM
To: Elena Ranguelova <e.ranguelova@esciencecenter.nl>
Cc: dianna-ai <dianna-ai@esciencecenter.nl>
Subject: Re: NEWSGAC paper

Elena,


Thanks for the user study. It looks fine. Here are some comments:

User name: I would not use the first name of the project PI since this might suggest that he wrote the user story

Project name: please note that the project name is spelled NEWSGAC (final letter is a C)

Heatmap: I visualized a heatmap in the text domain as the input text with words marked in different colors. But then the ranking mentioned later in the user story would present the same information, only in a different format. Is this what you mean?

Output classes: missing in the user story is insight in the probabilities assigned to the various output classes (genres).

Another thing which could be added is a mention of the most similar training data item(s). This could also boost the confidence of the user in the model.
